"use client";
import { useEffect, useState } from "react";

type NewsSource = { title:string; url:string; publisher:string };
type Signal = { question:string; side:string; confidence:number; tier?:string|null; historyScore:number; historyScope:string; historySamples:number; newsScore:number; newsCount:number; newsEntity:string; newsSources:NewsSource[]; modelEdge:number; marketPrior?:number; timingScore?:number; crossBookArb:number; arbQualified?:boolean; arbExecutable?:boolean; arbGate?:string; route?:string; qualified:boolean; gate:string };
type Status = { connected?:boolean; mode?:string; markets?:number; positions?:number; deployed?:number; dailyPnl?:number; lastCycle?:string; signals?:Signal[]; evidence?:{gammaObservations?:number;transcriptSources?:Record<string,{documents:number;mentions:number}>}; strategy?:{directional?:boolean;arbDetection?:boolean;arbExecution?:boolean;maxPositionsPerContract?:number} };
const tags = [["105481","Trump Speech Mentions"],["105482","Politics Mentions"],["105486","NFL Mentions"],["100343","Mention Markets"]];
const weights = [["History · probability",35,"#6ee7b7"],["News · probability",25,"#38bdf8"],["Market prior · probability",14,"#d59b3a"],["Order book · timing",20,"#a78bfa"],["Momentum · timing",14,"#fbbf24"],["Model edge · hard gate",6,"#fb7185"]] as const;

export default function Home() {
  const [status,setStatus]=useState<Status>({connected:false});
  useEffect(()=>{const load=()=>fetch("/api/status",{cache:"no-store"}).then(r=>r.json()).then(setStatus).catch(()=>setStatus({connected:false}));load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[]);
  const connected=Boolean(status.connected);
  const signals=status.signals??[];
  const evidenceCount=status.evidence?.gammaObservations??0;
  return <main>
    <header className="topbar"><div className="brand"><span className="brandMark">M</span><div><b>MENTION EDGE</b><small>Polymarket execution console</small></div></div><div className="headerRight"><span className={`health ${connected?"online":""}`}><i/>{connected?"VPS CONNECTED":"VPS NOT CONNECTED"}</span><span className="clock">LIVE DATA · 15s</span></div></header>
    <section className="ticker"><span>MARKETS <b>{connected?status.markets??0:"—"}</b></span><span>MIN CONF <b>70%</b></span><span>MAX POSITIONS <b>5</b></span><span>ENTRY WINDOW <b>≤ 4H</b></span><span>SLIPPAGE <b>1–3%</b></span><span>MIN EDGE <b>6%</b></span></section>
    <section className="approval liveApproval"><div><span className="shield">!</span><div><strong>Real-money execution is active</strong><p>Orders can use the funded wallet when every confidence, liquidity, book, price, and timing gate passes.</p></div></div><span className="lockState">LIVE AUTHORIZED</span></section>
    <section className="hero"><div><p className="eyebrow">OPERATIONS / MENTION MARKETS</p><h1>Trade signals, risk,<br/><em>and execution.</em></h1><p className="lede">A fail-closed control surface for pre-event and live mention contracts. Every evidence score below comes from the running bot.</p></div><div className="modeCard"><span>EXECUTION MODE</span><strong>{status.mode||"LIVE"}</strong><p>Maker first → 20s → cancel → FAK taker</p></div></section>
    <section className="engineStrip"><div className="engineTitle"><p className="eyebrow">DIRECTIONAL + ARB WATCH + EXPOSURE ENGINE</p><strong>Separated probability and execution</strong><small>PROBABILITY → TIMING → EDGE → EXPOSURE → DIRECTIONAL ROUTE / ARB WATCH</small></div><div className="signalBox yes"><span>YES SIGNAL</span><b>70–100</b><small>maker-first directional</small></div><FlowNodes/><div className="signalCore"><i>ME</i><span>ROUTE<br/>CORE</span></div><FlowNodes reverse/><div className="signalBox no"><span>NO SIGNAL</span><b>0–30</b><small>maker-first directional</small></div></section>
    <section className="metrics"><Metric label="Scanned markets" value={connected?String(status.markets??0):"—"} note="Latest bot cycle"/><Metric label="Open positions" value={connected?String(status.positions??0):"—"} note="Maximum 5"/><Metric label="Capital deployed" value={connected?`$${(status.deployed??0).toFixed(2)}`:"—"} note="No aggregate dollar cap"/><Metric label="Daily P&L" value={connected?`${(status.dailyPnl??0)>=0?"+":""}$${(status.dailyPnl??0).toFixed(2)}`:"—"} note="Reporting only · no daily cutoff" accent/></section>
    <section className="grid"><article className="panel weights"><PanelHead eyebrow="STRATEGY ROLES" title="Probability, timing, and edge" badge="SEPARATED"/><div className="weightList">{weights.map(([label,value,color])=><div className="weight" key={label}><div><span>{label}</span><b>{value}%</b></div><div className="track"><i style={{width:`${value*2.6}%`,background:color}}/></div></div>)}</div><div className="tiers"><span><b>70–79</b>Tier C · $3</span><span><b>80–89</b>Tier B · $4</span><span><b>90–100</b>Tier A · $5</span></div></article>
    <article className="panel guardrails"><PanelHead eyebrow="HARD GATES" title="Risk guardrails" badge="FAIL CLOSED"/><div className="rules"><Rule label="Entry price" value="$0.16–$0.93"/><Rule label="Liquidity + volume" value="$800 minimum each"/><Rule label="Entry window" value="≤ 4h when known; unknown allowed"/><Rule label="Directional gates" value="70% confidence · 45 timing · 6% edge"/><Rule label="Exposure" value="5 total · 2 per contract"/><Rule label="$0.16–$0.37 exits" value="50% stop + trail"/></div></article></section>
    <section className="panel opportunities"><PanelHead eyebrow="LIVE EVIDENCE AUDIT" title="Evaluated contracts" badge={connected?`${evidenceCount} RESOLVED OBSERVATIONS`:"AWAITING VPS FEED"}/>{signals.length?<div className="evidenceTable">{signals.slice(0,8).map((signal,index)=><article className="evidenceRow" key={`${signal.question}-${index}`}><div className="signalSummary"><span className={`side ${signal.side.toLowerCase()}`}>{signal.side}</span><div><strong>{signal.question}</strong><small>{signal.route&&signal.route!=="NONE"?`${signal.route} · ${signal.qualified?"QUALIFIED":signal.arbGate}`:signal.gate}</small></div><b>{signal.confidence.toFixed(1)}%</b></div><div className="evidenceGrid"><Evidence label="History" value={`${signal.historyScore.toFixed(1)} · n=${signal.historySamples}`} note={signal.historyScope}/><Evidence label="Grounded news" value={`${signal.newsScore.toFixed(1)} · ${signal.newsCount} item${signal.newsCount===1?"":"s"}`} note={signal.newsEntity}/><Evidence label="Prior / timing" value={`${(signal.marketPrior??50).toFixed(1)} / ${(signal.timingScore??50).toFixed(1)}`} note="Probability prior / execution timing"/><Evidence label="Directional edge" value={`${signal.modelEdge.toFixed(1)}%`} note={`Arb ${signal.crossBookArb.toFixed(1)}% · ${signal.arbQualified?"watch":"not qualified"}`}/></div>{signal.newsSources.length>0&&<div className="sourceList">{signal.newsSources.map(source=><a href={source.url} target="_blank" rel="noreferrer" key={`${source.url}-${source.title}`}>{source.publisher}: {source.title}</a>)}</div>}</article>)}</div>:<div className="empty"><div className="radar"><i/></div><strong>{connected?"Waiting for the first completed scoring cycle":"Bot status file is not available"}</strong><p>{connected?"Evidence will appear after market discovery, history, news, and books finish.":"The dashboard reads only the bot’s shared status volume and never receives wallet secrets."}</p></div>}</section>
    <section className="grid charts"><article className="panel"><PanelHead eyebrow="BOOK PRESSURE" title="Hedge & skew helix" badge="LIVE FEED REQUIRED"/><Helix/></article><article className="panel"><PanelHead eyebrow="CONFIDENCE PATH" title="Signal reconstruction" badge="15s CYCLE"/><SignalChart/></article></section>
    <section className="grid lower"><article className="panel"><PanelHead eyebrow="VERIFIED DISCOVERY" title="Gamma event tags" badge="CHECKED 08 AUG 2026"/><div className="tagList">{tags.map(([id,label])=><div key={id}><code>{id}</code><span>{label}</span><b>VERIFIED</b></div>)}</div></article><article className="panel"><PanelHead eyebrow="ORDER ROUTE" title="Maker-first execution"/><div className="route"><div><b>01</b><span>Post-only GTC<strong>Join the book</strong></span></div><i>→</i><div><b>02</b><span>Wait 20 seconds<strong>Poll fills</strong></span></div><i>→</i><div><b>03</b><span>FAK fallback<strong>1–3% cap</strong></span></div></div></article></section>
    <footer><span>MENTION EDGE · OWNER-CONTROLLED LIVE EXECUTION</span><span>Last cycle: {status.lastCycle||"not connected"}</span></footer>
  </main>;
}
function Metric({label,value,note,accent=false}:{label:string;value:string;note:string;accent?:boolean}){return <article className={`metric ${accent?"accent":""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Rule({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Evidence({label,value,note}:{label:string;value:string;note:string}){return <div><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function PanelHead({eyebrow,title,badge}:{eyebrow:string;title:string;badge?:string}){return <div className="panelHead"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{badge&&<span>{badge}</span>}</div>}
function FlowNodes({reverse=false}:{reverse?:boolean}){return <div className={`flowNodes ${reverse?"reverse":""}`}>{[0,1,2,3,4].map(n=><i key={n}/>)}</div>}
function Helix(){return <svg className="chart" viewBox="0 0 600 190" role="img" aria-label="Order book hedge visualization"><path className="gridline" d="M0 45H600M0 95H600M0 145H600"/><path className="greenLine" d="M0 96 C25 8 50 8 75 96 S125 184 150 96 S200 8 225 96 S275 184 300 96 S350 8 375 96 S425 184 450 96 S500 8 525 96 S575 184 600 96"/><path className="redLine" d="M0 96 C25 184 50 184 75 96 S125 8 150 96 S200 184 225 96 S275 8 300 96 S350 184 375 96 S425 8 450 96 S500 184 525 96 S575 8 600 96"/><path className="goldLine" d="M0 96 C16 35 32 35 48 96 S80 157 96 96 S128 35 144 96 S176 157 192 96 S224 35 240 96 S272 157 288 96 S320 35 336 96 S368 157 384 96 S416 35 432 96 S464 157 480 96 S512 35 528 96 S560 157 576 96"/></svg>}
function SignalChart(){return <svg className="chart" viewBox="0 0 600 190" role="img" aria-label="Mention confidence signal chart"><path className="gridline" d="M0 45H600M0 95H600M0 145H600"/><path className="area" d="M0 150 L35 142 70 146 105 126 140 133 175 104 210 115 245 87 280 94 315 66 350 79 385 55 420 69 455 43 490 58 525 38 560 49 600 27 L600 190H0Z"/><path className="goldLine signal" d="M0 150 L35 142 70 146 105 126 140 133 175 104 210 115 245 87 280 94 315 66 350 79 385 55 420 69 455 43 490 58 525 38 560 49 600 27"/><circle cx="600" cy="27" r="7" className="pulse"/></svg>}
